# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2021-09-10 16:04:01
"""
import arcpy
from sys import argv
import arcpy
import numpy
def getAreaRaster(rst):
    arr = arcpy.da.TableToNumPyArray(rst, "COUNT")
    a,= arr.tolist()[0]
    return a 

def LandEncroachmentPercentage(crf_name="land_encroachment.crf", geometry="unique_square", output_table="C:\\Users\\Viz1\\Documents\\ArcGIS\\Projects\\SuperSample\\SuperSample.gdb\\ZonalSt_unique_1"):  # LandEncroachmentPercentage

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageExt")
    arcpy.CheckOutExtension("ImageAnalyst")


    # Process: Zonal Statistics as Table (Zonal Statistics as Table) (sa)
    ZonalSt_unique_1 = "C:\\Users\\Viz1\\Documents\\ArcGIS\\Projects\\SuperSample\\SuperSample.gdb\\ZonalSt_unique_1"
    arcpy.sa.ZonalStatisticsAsTable(in_zone_data=geometry, zone_field="OBJECTID", in_value_raster=crf_name, out_table=ZonalSt_unique_1, ignore_nodata="DATA", statistics_type="ALL", process_as_multidimensional="ALL_SLICES", percentile_values=[90])
    .save(Zonal_Statistics_as_Table)


    # Process: Polygon to Raster (Polygon to Raster) (conversion)
    custom_raster = "C:\\Users\\Viz1\\Documents\\ArcGIS\\Projects\\SuperSample\\SuperSample.gdb\\unique_square_PolygonToRaster"
    arcpy.conversion.PolygonToRaster(in_features=geometry, value_field="OBJECTID", out_rasterdataset=custom_raster, cell_assignment="CELL_CENTER", priority_field="NONE", cellsize="C:\\Users\\Viz1\\Documents\\ArcGIS\\Projects\\SuperSample\\land_encroachment_Subset.crf")

    # Process: Calculate Value (Calculate Value) ()
    if custom_raster:
        area_raster = getAreaRaster(r"custom_raster")

    # Process: Calculate Field (Calculate Field) (management)
    if area_raster and custom_raster:
        output_table = arcpy.management.CalculateField(in_table=ZonalSt_unique_1, field="percentage_land_encroachment", expression=f"round((!COUNT!/{area_raster})*100,2)", expression_type="PYTHON3", code_block="", field_type="TEXT")[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\Viz1\Documents\ArcGIS\Projects\SuperSample\SuperSample.gdb", workspace=r"C:\Users\Viz1\Documents\ArcGIS\Projects\SuperSample\SuperSample.gdb"):
        LandEncroachmentPercentage(*argv[1:])
